- name: Include labels generator
  ansible.builtin.include_role:
    name: labels_generator

- name: Dozzle container
  community.docker.docker_container:
    name: "{{ app_name }}"
    image: amir20/dozzle:latest
    pull: true
    restart_policy: "unless-stopped"
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels: "{{ labels }}"
