- name: Include labels generator
  ansible.builtin.include_role:
    name: labels_generator

- name: Portainer container
  community.docker.docker_container:
    image: portainer/portainer-ce:latest
    pull: true
    name: "{{ app_name }}"
    restart: true
    restart_policy: "unless-stopped"
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ app_data_dir }}:/data"
    command: "-H unix:///var/run/docker.sock"
    labels: "{{ labels }}"
