---
- name: Watchtower container
  community.docker.docker_container:
    name: watchtower
    image: nickfedor/watchtower
    pull: true
    restart_policy: "always"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
    command: --cleanup
    networks:
      - name: "{{ docker_network }}"
    env:
      WATCHTOWER_NOTIFICATION_URL: "telegram://{{ telegram_alerts_bot_token }}@telegram?chats={{ telegram_alerts_chat_id }}"
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: "{{ ansible_host }}"
      WATCHTOWER_SCHEDULE: "{{ watchtower_schedule | default('0 0 9 * * *') }}"
