set nocompatible              " be iMproved, required
filetype off                  " required
set t_Co=256
set background=dark
colorscheme monokai
filetype plugin indent on    " required
syntax on
" set laststatus=2
call plug#begin()
Plug 'bling/vim-airline'
Plug 'bronson/vim-trailing-whitespace'
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
call plug#end()
set laststatus=2
