- name: Create HackMD user
  community.postgresql.postgresql_user:
    name: "{{ app_name }}"
    password: "{{ app_name }}"

- name: Create HackMD database
  community.postgresql.postgresql_db:
    name: "{{ app_name }}"
    owner: "{{ app_name }}"

- name: Create HackMD data directory
  ansible.builtin.file:
    path: "{{ data_dir }}"
    state: directory
    owner: "10000"
    group: "10000"
  become: true

- name: Include labels generator
  ansible.builtin.include_role:
    name: labels_generator

- name: HackMD container
  community.docker.docker_container:
    image: quay.io/hedgedoc/hedgedoc:latest
    pull: true
    name: "{{ app_name }}"
    restart_policy: "unless-stopped"
    restart: true
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - "{{ app_data_dir }}:/hedgedoc/public/uploads"
    env:
      CMD_DB_URL: "postgres://{{ app_name }}:{{ app_name }}@postgres:5432/{{ app_name }}"
      CMD_DOMAIN: "{{ app_name }}.{{ ansible_host }}"
    labels: "{{ labels }}"
