- name: Copy homer config file
  ansible.builtin.template:
    src: homer-config.yml
    dest: "{{ data_dir }}/homer/config.yml"

- name: Copy homer icons dir
  ansible.builtin.copy:
    src: icons
    dest: "{{ data_dir }}/homer"

- name: homer container
  community.docker.docker_container:
    name: homer
    image: b4bz/homer:latest
    pull: true
    restart_policy: "unless-stopped"
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - "{{ data_dir }}/homer:/www/assets"
    user: "1000:1000"
    labels:
      traefik.enable: "true"
      traefik.http.routers.homer.rule: "Host(`{{ ansible_host }}`)"
      traefik.http.services.homer.loadbalancer.server.port: "8080"
