---
- name: Run segments-go container
  community.docker.docker_container:
    image: olegsmedyuk/segments:latest
    name: segments
    restart: true
    restart_policy: "unless-stopped"
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - "{{ data_dir }}/segments-go/segments.db:/app/segments.db"
    labels:
      traefik.enable: "true"
      traefik.http.routers.segments-go.entrypoints: "websecure"
      traefik.http.routers.segments-go.tls: "true"
      traefik.http.routers.segments-go.tls.certresolver: "letsencrypt"
      traefik.http.routers.segments-go.rule: "Host(`segments.{{ ansible_host }}`)"
      traefik.http.services.segments-go.loadbalancer.server.port: "8080"
      traefik.http.routers.segments-go.middlewares: "no-auth-chain@file"
