- name: Include labels generator
  ansible.builtin.include_role:
    name: labels_generator

- name: Gitea container
  community.docker.docker_container:
    name: "{{ app_name }}"
    image: "gitea/gitea:latest"
    pull: true
    restart_policy: "unless-stopped"
    restart: true
    networks:
      - name: "{{ docker_network }}"
    env:
      TZ: "{{ tz }}"
      DB_TYPE: sqlite3
      START_SSH_SERVER: "false"
      SSH_PORT: ""
      DOMAIN: "{{ app_name }}.{{ ansible_host }}"
      ROOT_URL: "http://{{ app_name }}.{{ ansible_host }}"
    volumes:
      - "{{ app_data_dir }}:/data"
    labels: "{{ labels }}"
