#ENC[AES256_GCM,data:tl3+J/YsQYBOj4V9HOQ3aV34oYfroWiaT7RuKSzDZeeoOpR9zSdxchdQVxcAL2Lc3mPW03EwaEyE0zdyYH+59cM6iDZLPbBG431uSnI=,iv:IvyxLt7pF4Z1wfXpP9YXXw0UjNd3NGX4rklhD+pW68s=,tag:KxWskxZofZxdeQp7reNSPg==,type:comment]
#ENC[AES256_GCM,data:X1EfJByMKrOlMUinwQiopHmvsfE4OPnBwVWRlEnyKnZAHZi9cJ+BucAFFIkDF9N4pSWE+nrV1Tzq6H3A4HxIRHjVPnGYSPkvI5/l1JqFmmDuc4yUaWU7E1Yf,iv:cpJYnpThD++Hk8PIFPrmAZ++mtLwIyMSq1LeYXQo3Jo=,tag:Uj1ITpZk9ppv1jF8+/AggA==,type:comment]
#ENC[AES256_GCM,data:10BlXTZEdlLlSmDVhMFGpYsERoE0X3/nHzV3iQ7slJP3+FBYqAiWIb1pz6Tmiks2pffQBAr91pwt6XhvxrNB/EVPSMwEfg==,iv:/1d32nruwUIheSIfh8IbxZHQQ+DV84XluhJHAY6GRMc=,tag:CbrmoNTt1AsGgRbc5+CQqg==,type:comment]
bw_client_id: ENC[AES256_GCM,data:C8P/g/zi1k7K4OpNdwROMUHX/dRIxgL8dhuRKOtIqBUZid5dQOr8Bvc=,iv:vN6RRstqdZUbCoBKhmyvQM4Dg9pkPpwszZW8YPN+OTc=,tag:bP3lRZ7U35HF3lRZIeVR+A==,type:str]
bw_client_secret: ENC[AES256_GCM,data:5j7Wge6EtGfsjy0N6KdNdeg9YUsI6UUbpSw2cAA2,iv:O+Fx/Uhad4KKcs9nH00aumJtQdaX+0MBy3+CNiep330=,tag:dJ4ZJ+5NZt2FMBPF7KNBkQ==,type:str]
bw_password: ENC[AES256_GCM,data:MaVXSs4fRCVCZJnLJ+R/9Xl0f45V+SMR5w==,iv:OxSnST+fM2e7fjpHZ8qfb0BYxYxQ38inBbnk/sUK1iI=,tag:M+31gI1GgLdx9HfQ+BC4cw==,type:str]
#ENC[AES256_GCM,data:ixBGPlbnOv367azCMEXH2+OF3TrWR8zM9t1PliBFGluJ6VdTz+xRVlIBatuwPiP/JbC4YT0zO+bBmK0ysfA=,iv:5+KqXCL8jJjCe7+RqO15FZUaAtImXCUMdU6jJ4WnUjY=,tag:Q0XaT/hMiE3zn3MLYYSOew==,type:comment]
b2_account_id: ENC[AES256_GCM,data:bShPsufj58uxSu2gV0N8q3slpUsw9uzh8Q==,iv:jeBZuSUJHsPSZsKe7A3zMFZTgSGGgYUBd6j4jX7OlQg=,tag:7hiy+aqYr0sj96k8ITgsXA==,type:str]
b2_application_key: ENC[AES256_GCM,data:ZE2lTXHqtxFA4JUCTEwHrfaVg+rYdT6sq8OTZ8dPmw==,iv:Wd4h6DT2IdL3TLJpumTBlDHleC74EKjP+LBPtMWBsWo=,tag:qXM0Sx9VQXyngzgSAQw19g==,type:str]
navidrome_admin_user: ENC[AES256_GCM,data:RCsyfFE=,iv:a94w3QmqrUa+wIMgMGsWWuBqMUBdsBQzjUXeu+x6+Ak=,tag:3injQB/EShrwvjlNYtC55Q==,type:str]
navidrome_admin_password: ENC[AES256_GCM,data:aWDaiZGBZBFdvesOoE0BUhBxZ0U=,iv:jFJvmWQkdZzT3AlL9R9iw48j5CDOobGCrUH/X4/r3MI=,tag:YQk4xMglFRnQFYaxCBQIVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYkx4UWdrQkw4TjBKZjJF
            M1FZNmRwVGd2SUZvK01VTGlxdnZFQTQ4U3dnCjN3LzIyYUhFMVU0TXJOSkpITTYz
            YWE5RkZWMDZvWmdNTStRakxyWVdZOUEKLS0tIHJqeUpZeXVUa3EvRFE4dnBRRmFv
            OFVXb0RXOGRmSmI2dWlUQVhsMGZOOXcK6q9cI/un+GKrwJGDStbj8iAr59z+/VY1
            A3vRFnJHPbJsxz+H1AO2e/K1Mr4b0GSXsP3wfU0wUn1xopLw9BDtJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15q64pz4lwtf95vw3afmku5pzuexnsshm6ndfxhhnkqzj6rc3vc9su8fefq
    lastmodified: "2026-06-01T14:27:42Z"
    mac: ENC[AES256_GCM,data:rAJyDT7Ylr6SZ9PByPKvb94vM228t1unoAYXOVcyKd7SuMU/5+vssKkW1/oxjAyXPZWj1/gInvk/aUvnGSHWryH3vwwowy4P9CwOJEY1IDYFSw+CeMmNwxy5PRx5O2wGrJ55uqICJuZeDyKL6nptjDDtFbx2kGN0VRnLSG1TVao=,iv:+achvvZpHVq90ZeeK3OSffbkKyVNiGfczoEcbRkTi0o=,tag:tIDrE4TrxnOCfStOouRcWw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
