#ENC[AES256_GCM,data:ErwKKRldlD62nio2d6olgWG8SnbzpEyABv1hkq2k2PXP1g==,iv:3KqzSM6jiqWHKZZP3Q57dYHp264Lb+mPCPdMo8hySCY=,tag:Dbq+GvGZVEyRRGB6K0/4YQ==,type:comment]
#ENC[AES256_GCM,data:M1d1RpB2rBZS/RSxI8JGtzuW/fAqRaHpjNDIywHBe4ffbpYWJxAqo8IOGf8/oUQF3p6xcHGfL+oZ+w==,iv:/PihzoeM00JbDMDbKD8M4IfeDmAzCVnK76swGcU+ehQ=,tag:rDkTUboaocPLfqqHQSUt7w==,type:comment]
#ENC[AES256_GCM,data:HYVPSm5YZ0f0fGCVExVPCqoiACb5PDjljfYmdliqx4kzZVgh8ZSfLWcwVsEWrAHy+s1J0FIw8FhOh/gzIRMEWufUbr/QFU10,iv:yt466xWFDUd63KM4uxldXQqLz0873Vw9xY+wL99hefg=,tag:Rs8n+9x3QEkuWOLKsaOWbQ==,type:comment]
#ENC[AES256_GCM,data:iy73//9mgIFzbNl5CFNTIG/3uMoizCWysl/a7WBaSqMG6ZWsrx/GhOMhMNoixNDCWB8PxQdClVxIfM9fBiPpNTVX0tmF5D/A9TlUzzw=,iv:+vicRfZTa6R0JLXeor1F19uG51uC/6jVvXIxJ65MIYg=,tag:0N1i0zi6XkAtQ2+Or7aRmA==,type:comment]
home_meters_bot_token: ENC[AES256_GCM,data:IQpHdGzFpoUv5chLNtmbodLLjoXFArPuHn+rzaRfi6tCw0N7RPbeQIkDIOn9vQ==,iv:5e5/9brKE2FKHQSNRXFyKH2UGepNwzDbkbqezk8Mn3A=,tag:P61Hj7mhNkx7kx8b5yB3Aw==,type:str]
home_meters_notify_chat: ENC[AES256_GCM,data:tcySJ+eVdgQakVC2dBM=,iv:naqS1/TmyXVYir7DI4aE0MekTbM1oolJMOlEPulJ62s=,tag:DlUIMEyngDdD/iJaWd+xYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWURkcGE4OGhVbS9VSE0w
            VjFJeFhpRmZFWllsRGYzNFpHMmlSYnJoNEhrCkl2bUljaHg2cGN3dkFWSFhsbzh0
            YVY4dFV4cXZQL0YxZWZBd3FSMkJBVmMKLS0tIGYzcUlUdHp6UzNXb0JJTGlCVXVZ
            QkRSV2wvaEtRdXMwVTROeXNsYUtyakkKvEFJ17hwO0HdeSX84KCNj5p1esA3HdJ2
            o2ljPlz85uBd3JH7fvG4aPQm6Q08jhNkh9rLte6RhZ6XYPOLRkSf0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15q64pz4lwtf95vw3afmku5pzuexnsshm6ndfxhhnkqzj6rc3vc9su8fefq
    lastmodified: "2026-05-31T13:26:15Z"
    mac: ENC[AES256_GCM,data:VtLynOkBhLi5xlhp5UJC1bwp0BlfuwBpSDX3P79f9yREqp5KLsCnu1HKAI75rKTrr09a2WiN9y0rSXe9kaTeAJVYN9dupchoLePshamUqwaEjc4yPH8XiRH794XAkSJLsSvAkXm8es03CZKpUj0ivKvbn7Eme1fscX0WxTN5Y+I=,iv:CR5AXLbjiw9of+Hp7RNvjUGyy450CN5FZMGC708UrIQ=,tag:C8Q0jfcgpaysGLx5mVcMGA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
