#ENC[AES256_GCM,data:zQXD2I4RFXtkAClH1tBjZUvhFpBlvdYujcsWGJRTA6fzBY16sRBMcr7iA4YQI39/hDUESANZ0HpNU+GyR1M+CHvjWV6FspTaJRkMRdn3kmbsOx0NM0lvcyA6plV+iy+L,iv:GSMZfdfFB9vZkeTftJA9ji/ExVG9LPlPtiFFAoEb86U=,tag:AMuGgSkzL24DB0pdCPTF7g==,type:comment]
#ENC[AES256_GCM,data:LUD512mW5HM28PFSbVqZqzR60wmbcjsg5dB52YysNunOFvfm2uEwNIJ5oGh/JJcU8rAGAixIwpcyq5m/6f/wpyhSeC+6LzTvc5cW4SlEeBrLpL5VXGyzgCJq,iv:ncWJp+3/hHf2kzOXTKnGc/SI7YIM+7pgJccbwxCF1ns=,tag:+R3NS1D9gBN2O2fwLuJAsA==,type:comment]
#ENC[AES256_GCM,data:k/L3wQw1IWEN/KF9nF1Jt1wP1+xXNTbSmw+jDwCiUFrmyDgnwAvT8Fy1DAObGfqCr9AcVGDv29Ul4TohMZYQI3q+q92USqqQbUl2uKzOVQ==,iv:BQOIElgwzeSy4BiVq8YgJfudAm9Lpi9eKvafeNfSiBk=,tag:PZmIonbGO4p3dvjIwirShg==,type:comment]
telegram_alerts_bot_token: ENC[AES256_GCM,data:DqywRP+/IF0zorcp2MBXTUjQr97l+xXov3tCYUyq2BYQ/crZZ6HHvFvrTVKA2Q==,iv:HMSRfIHPDLbk4JnH3CyNGlcw41fm0GFLn/omNzT35Tw=,tag:kDb/y1zJ/rW1b8jsNs+yeA==,type:str]
telegram_alerts_chat_id: ENC[AES256_GCM,data:EjPKEF0UzzWI,iv:COWyQkk9JhsCPdGQHI7ThaOoxVEGvileO/0lo7zrDBA=,tag:Q+DBVAETZAP45/0oAYVJjg==,type:int]
openweather_api_key: ENC[AES256_GCM,data:WNbpbF7c9KCUrk/9hMWdGOSTj7eZwwE5KgLGo1GHMjY=,iv:Rw28cS6myby3kHXZDG66L2hdwcO+0bZxRBRzBUxWY0g=,tag:7oGogFw9AqAPHriS13jwKA==,type:str]
default_local_admin_password: ENC[AES256_GCM,data:F88ZJ4DoBK0=,iv:pwr1nmQ/KqHpUlUgWR49M5sS2VbZeyO70emzJPp8Cqc=,tag:QhONSWI6YBGqVtm85J2lAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZWw2V29SU3BlVVltQkxX
            bDcrOXlGOVdtTnozVCs2WUgremtJYXlDeTAwCnI1aEN5dGY3L0hCdTNHbkdKajRR
            Q0Z2ZE5DTldJbFp3NHMxTVJnUnVXVUkKLS0tIGo0Vkd5bmZka2J3SHNuNTczMEZp
            SzJaZlA4Zi91SXZSMWV4dkpJaVg1ZlUKbdS1PxpVr7GCmmro4j3z5UYZZ+T41Grn
            uqRwrlos7yfvMPSaD7cP5A8CtXOY78ExCO41TWoh0yhcyF1NIKMNPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15q64pz4lwtf95vw3afmku5pzuexnsshm6ndfxhhnkqzj6rc3vc9su8fefq
    lastmodified: "2026-06-02T15:41:39Z"
    mac: ENC[AES256_GCM,data:yKsFGDgdWqZt8gUkM6zHgdcshUrvim4GK00i8+U9e2uecRKGPN9k6O9cEFF9aI5700P6D8BOj2u9KkljRxP4XRuwONbpYrMX50kQAPGMp08Fb80uUneAq+GrGCWA6ENhS2Qx8s+gauwjIJtYCNbKK/4SHd/e8FHLKGaSLSWWvoA=,iv:MIqChJ4xaG0l2weEvHCVW7nPA1IzIQ3Wp8nKmUmqEJ0=,tag:RULiqp5+PfEaH/kDhqMHdw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
