- name: Include labels generator
  ansible.builtin.include_role:
    name: labels_generator

- name: Jellyseerr container
  community.docker.docker_container:
    name: "{{ app_name }}"
    image: fallenbagel/jellyseerr:latest
    restart: true
    restart_policy: "unless-stopped"
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - "{{ app_data_dir }}:/app/config"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    env:
      TZ: "{{ tz }}"
    labels: "{{ labels }}"
