set number
set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'git://git.wincent.com/command-t.git'
Plugin 'vim-airline/vim-airline'
Plugin 'rakr/vim-one'
call vundle#end()            " required

filetype plugin indent on    " required
set laststatus=2
set tabstop=2 shiftwidth=2 expandtab
let g:airline_theme='one'
let g:airline_powerline_fonts = 1
colorscheme one
