- applications:
    - whoami:
        href: https://whoami.{{ ansible_host }}
        description: "Whoami to debug"
        icon: "mdi-head-question"
        container: "whoami"
        server: "local-docker"

    - Traefik:
        href: https://traefik.{{ ansible_host }}
        description: "Traefik dashboard"
        icon: "traefik"
        container: "traefik"
        server: "local-docker"

    - Dozzle:
        href: https://dozzle.{{ ansible_host }}
        description: "Docker logs"
        icon: "dozzle"
        container: "dozzle"
        server: "local-docker"

    - rsstt:
        href: https://rsstt.{{ ansible_host }}
        description: "RSS to Telegram"
        icon: "mdi-rss"
        container: "rsstt"
        server: "local-docker"

    - Commeilfaut:
        href: https://commeilfaut.{{ ansible_host }}/admin
        description: "Ceilings shop admin"
        icon: "mdi-ceiling-light"
        container: "ceilings-app"
        server: "local-docker"

    - Lessons:
        href: https://lessons.{{ ansible_host }}
        description: "Kids' lessons tracker"
        icon: "mdi-school"
        container: "lessons"
        server: "local-docker"

    - Home meters:
        href: https://meters.{{ ansible_host }}
        description: "Utility meter readings"
        icon: "mdi-meter-electric"
        container: "home-meters"
        server: "local-docker"

    - Pihole:
        href: https://pihole.{{ ansible_host }}/admin
        description: "Network-wide ad blocking"
        icon: "pi-hole"
        container: "pihole"
        server: "local-docker"

- tools:
    - Segments:
        href: https://segments.{{ ansible_host }}
        description: "Segments app"
        icon: "mdi-segment"
        container: "segments"
        server: "local-docker"
    - Glances:
        href: https://glances.{{ ansible_host }}
        description: "System monitoring"
        icon: "glances"
    - CrowdSec:
        href: https://crowdsec.{{ ansible_host }}
        description: "Security engine dashboard"
        icon: "crowdsec"
        container: "crowdsec-web-ui"
        server: "local-docker"

- proxy:
    - Home Assistant:
        href: https://ha.conformist.name
        description: "Home automation"
        icon: "home-assistant"
    - Nextcloud:
        href: https://files.conformist.name
        description: "Nextcloud"
        icon: "nextcloud"

    - Navidrome:
        href: https://music.{{ ansible_host }}
        description: "Music server"
        icon: "navidrome"

    - Router:
        href: https://router.conformist.name
        description: "Router"
        icon: "keenetic"

- home:
   - Home:
        href: http://bee.home
        description: "Beelink homepage"
        icon: "homepage"
