---
- name: Add Caddy GPG key
  ansible.builtin.apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    keyring: /etc/apt/trusted.gpg.d/caddy-stable-archive-keyring.gpg
    state: present
  become: true

- name: Add apt repo
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
    state: present
    filename: caddy
  become: true

- name: install caddy
  ansible.builtin.apt:
    name:
      - caddy
  become: true

- name: Create data dir
  ansible.builtin.file:
    path: "{{ data_dir }}/caddy"
    state: directory

- name: Copy index.html homepage
  ansible.builtin.copy:
    src: index.html
    dest: "{{ data_dir }}/caddy/index.html"
  become: true

- name: Copy Caddyfile
  ansible.builtin.template:
    dest: "/etc/caddy/Caddyfile"
    src: Caddyfile.j2
  register: caddy_config
  become: true

- name: Restart caddy
  ansible.builtin.systemd:
    state: restarted
    name: caddy
  when: caddy_config.changed
  become: true
