---
- name: Set Vim as default editor
  ansible.builtin.shell: >
    update-alternatives --set editor /usr/bin/vim.basic
  become: true

- name: Install vim, git, fonts-powerline
  ansible.builtin.apt:
    name:
      - vim
      - git
      - fonts-powerline
    state: present
  become: true

- name: Create config dir
  ansible.builtin.file:
    path: "{{ vim_dir }}"
    state: directory
    mode: "0755"

- name: Copy main configuration file
  ansible.builtin.copy:
    src: vimrc
    dest: "{{ vim_dir }}/vimrc"

- name: Clone Vundle plugin
  ansible.builtin.git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ vim_dir }}/bundle/Vundle.vim"

- name: Install Vundle plugins
  ansible.builtin.shell: >
    echo -ne '\n' | vim -E -s -c "source {{ vim_dir }}/vimrc" -c PluginInstall -c qa || [ $? = 1 ] && exit 0 || exit 2
  changed_when: false # suppress changing
