export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""  # set to empty to use starship
export LANG="en_US.UTF-8"
plugins=(
    brew
    git
    iterm2
    macos
    mise
    pre-commit
    python
    uv
    you-should-use
)
zstyle :omz:plugins:iterm2 shell-integration yes

source $ZSH/oh-my-zsh.sh

export HISTIGNORE="&:ls:[bf]g:exit"
export HISTSIZE=40000
export HISTFILESIZE=1000000
unsetopt share_history # don't share history between sessions

setopt inc_append_history_time # save the time stamp when the command was entered
setopt interactivecomments # allow comments in interactive shell

# autojump
if (( $+commands[brew] )); then
  file=$HOMEBREW_PREFIX/etc/profile.d/autojump.sh
  if [[ -f "$file" ]]; then
    source "$file"
    found=1
  fi
fi

# zsh-completions
[[ -s /opt/homebrew/share/zsh-completions ]] && fpath=(/opt/homebrew/share/zsh-completions $fpath)
compinit -u

# Run 'ls' after 'cd'
function chpwd_ls {
    ls
}
add-zsh-hook chpwd chpwd_ls

export PATH="/Users/oleh/.local/bin:$PATH"
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
export CPPFLAGS="-I/opt/homebrew/include"
export LDFLAGS="-L/opt/homebrew/lib"

eval "$(starship init zsh)"

export HOMEBREW_NO_ENV_HINTS=1
export GPG_TTY=$(tty)

eval "$(/opt/homebrew/bin/mise activate zsh)"

# extra plugins from homebrew
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh  # must be first
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh

eval "$(zoxide init zsh)"
