# list all available commands
default:
  @just --list --unsorted

############ AWS SSO START ############

# Check AWS CodeArtifact token to not refresh if not needed
[group('CodeArtifact')]
check-ca-token:
    @echo "Checking AWS token validity..."
    @aws sts get-caller-identity --profile legacy-prod >/dev/null 2>&1 && \
    pip config get global.index-url | grep -q "wikr-packages" && \
    echo "AWS token is valid" || (echo "AWS token expired or not configured" && exit 1)

# Login pip to AWS CodeArtifact (creates ~/.config/pip/pip.conf)
[group('CodeArtifact')]
login-ca:
    @echo "Logging into AWS SSO..."
    aws sso login --profile legacy-prod
    @echo "Configuring CodeArtifact..."
    aws codeartifact login \
      --profile legacy-prod \
      --tool pip \
      --repository vendor-lambda \
      --domain wikr-packages \
      --domain-owner 756650017283

# Create or update ./uv.toml in the current project for AWS CodeArtifact
[group('CodeArtifact')]
[no-cd]
update-uv-conf:
    #!/bin/sh
    file_path="uv.toml"
    pip_url="$(pip config get global.index-url 2>/dev/null || echo '')"
    cat > "$file_path" << EOF
    [[index]]
    name = "pypi"
    url = "https://pypi.org/simple/"

    [[index]]
    name = "wikr-packages"
    url = "$pip_url"
    EOF
    echo "uv.toml updated at $file_path"

# Shortcut to check and login to AWS CodeArtifact, then write ./uv.toml
[group('CodeArtifact')]
[no-cd]
codeartifact-login:
    @just check-ca-token || just login-ca
    just update-uv-conf

############ AWS SSO END ############

# uv create virtual environment
[group('uv')]
uv-init VERSION='3.13':
    uv venv --python {{ VERSION }} --seed
