global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "beelink"
    static_configs:
      - targets:
          - "{{ ansible_host }}:9100"
          - "{{ ansible_host }}:9177"
  - job_name: "home-pc"
    static_configs:
      - targets:
          - "192.168.1.199:9182"

