---
- name: Create project directory
  ansible.builtin.file:
    path: "{{ app_data_dir }}"
    state: directory
    mode: "0755"

- name: Install Node via curl script
  ansible.builtin.shell: |
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
    apt-get install -y nodejs
  become: true

- name: Checkout repository
  ansible.builtin.git:
    repo: git@github.com:conformist-mw/ceilings.git
    dest: "{{ app_data_dir }}"
    version: master
    force: true
    update: true
  register: git_checkout

- name: Update compose stack
  when: git_checkout.changed
  block:
    - name: Install frontend dependencies
      ansible.builtin.command: npm install
      args:
        chdir: "{{ app_data_dir }}/frontend"

    - name: Build frontend
      ansible.builtin.command: npm run build
      args:
        chdir: "{{ app_data_dir }}/frontend"

    - name: Copy production.env
      ansible.builtin.template:
        src: production.env
        dest: "{{ app_data_dir }}/backend/.env"
        mode: "0644"
      vars:
        secret_key: "{{ lookup('community.general.bitwarden_secrets_manager', 'df964675-f358-4caa-b54b-b30e01127dda').value }}"
        sentry_dsn: "{{ lookup('community.general.bitwarden_secrets_manager', 'b65b5c10-de66-4574-bd5e-b30e01129535').value }}"

    - name: Run docker compose build
      ansible.builtin.command: docker compose build
      args:
        chdir: "{{ app_data_dir }}/backend"

    - name: Run migrations
      ansible.builtin.command: docker compose run --rm ceilings python manage.py migrate
      args:
        chdir: "{{ app_data_dir }}/backend"

    - name: Run collectstatic
      ansible.builtin.command: docker compose run --rm ceilings python manage.py collectstatic --noinput
      args:
        chdir: "{{ app_data_dir }}/backend"

    - name: fix file permissions
      ansible.builtin.command: chown -R "{{ ansible_user }}:" static
      args:
        chdir: "{{ app_data_dir }}/backend"
      become: true

    - name: Restart services
      ansible.builtin.command: docker compose up -d
      args:
        chdir: "{{ app_data_dir }}/backend"
