---
- name: RSS To Telegram bot
  community.docker.docker_container:
    image: rongronggg9/rss-to-telegram:dev
    name: rsstt
    restart_policy: "unless-stopped"
    networks:
      - name: "{{ network }}"
    env:
      TOKEN: "{{ rsstt_bot_token }}"
      MANAGER: "{{ tg_chat_id | int }}"
    volumes:
      - "{{ data_dir }}/rsstt:/app/config"
