---
- name: Copy rsstt config
  ansible.builtin.template:
    dest: "{{ data_dir }}/rsstt/config.json"
    src: config.json
  become: true

- name: RSSTT container
  community.docker.docker_container:
    image: olegsmedyuk/rsstt:latest
    pull: true
    name: rsstt
    restart: true
    restart_policy: "unless-stopped"
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - "{{ data_dir }}/rsstt/config.json:/config.json:ro"
      - "{{ data_dir }}/rsstt/feed.db:/data/feed.db"
    labels:
      traefik.enable: "true"
      traefik.http.routers.rsstt.entrypoints: "websecure"
      traefik.http.routers.rsstt.tls: "true"
      traefik.http.routers.rsstt.tls.certresolver: "letsencrypt"
      traefik.http.routers.rsstt.rule: "Host(`rsstt.{{ ansible_host }}`)"
      traefik.http.services.rsstt.loadbalancer.server.port: "8080"
      traefik.http.routers.rsstt.middlewares: "no-auth-chain@file"
