---
- name: Create project directory
  ansible.builtin.file:
    path: "{{ app_data_dir }}"
    state: directory
    mode: "0755"

- name: Checkout repository
  ansible.builtin.git:
    repo: git@github.com:conformist-mw/ceilings.git
    dest: "{{ app_data_dir }}"
    version: master
    force: true
    update: true
  register: git_checkout

- name: Update compose stack
  when: git_checkout.changed
  block:
    - name: Copy production.env
      ansible.builtin.template:
        src: production.env
        dest: "{{ app_data_dir }}/backend/.env"
        mode: "0644"
      vars:
        secret_key: "{{ commeilfaut_secret_key }}"
        sentry_dsn: "{{ commeilfaut_sentry_dsn }}"

    - name: Run docker compose build
      ansible.builtin.command: docker compose build
      args:
        chdir: "{{ app_data_dir }}/backend"

    - name: Run migrations
      ansible.builtin.command: docker compose run --rm ceilings python manage.py migrate
      args:
        chdir: "{{ app_data_dir }}/backend"

    - name: Restart services
      ansible.builtin.command: docker compose up -d
      args:
        chdir: "{{ app_data_dir }}/backend"
