install:
    ansible-galaxy install -r requirements.yml

encrypt:
	ansible-vault encrypt vault.yml

decrypt:
	ansible-vault decrypt vault.yml

deploy-rpi:
	ansible-playbook rpi.yml -e "@vault.yml"

deploy-bee:
    ansible-playbook beelink.yml -e "@vault.yml"

deploy-do-vps:
	ansible-playbook do_vps.yml -e "@vault.yml"

syntax-check:
	ansible-playbook do_vps.yml --syntax-check
	ansible-playbook rpi.yml --syntax-check
