set dotenv-load

install:
    ansible-galaxy install -r requirements.yml

deploy-bee:
    ansible-playbook beelink.yml

deploy-hetzner:
	ansible-playbook hetzner.yml

deploy-mac:
  ansible-playbook macos.yml

syntax-check:
	ansible-playbook beelink.yml --syntax-check
	ansible-playbook hetzner.yml --syntax-check
