set dotenv-load

install:
    ansible-galaxy install -r requirements.yml

deploy-bee:
    ansible-playbook beelink.yml"

deploy-hetzner:
	ansible-playbook hetzner.yml

syntax-check:
	ansible-playbook do_vps.yml --syntax-check
	ansible-playbook rpi.yml --syntax-check
