---
- name: Create NC user
  community.postgresql.postgresql_user:
    name: "nextcloud"
    password: "nextcloud"

- name: Create NC database
  community.postgresql.postgresql_db:
    name: "nextcloud"
    owner: "nextcloud"

- name: Nextcloud container
  community.docker.docker_container:
    image: nextcloud:latest
    name: nextcloud
    restart: true
    restart_policy: "unless-stopped"
    networks:
      - name: "{{ docker_network }}"
    ports:
      - "10080:80"
    volumes:
      - "{{ data_dir }}/nextcloud:/var/www/html"
    env:
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.{{ ansible_host }}"
      NEXTCLOUD_ADMIN_USER: "admin"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ lookup('community.general.bitwarden_secrets_manager', 'c6f1a5a9-a34f-404d-ad2a-b26d0130b756').value }}"
      POSTGRES_HOST: "postgres"
      POSTGRES_DB: "nextcloud"
      POSTGRES_USER: "nextcloud"
      POSTGRES_PASSWORD: "nextcloud"
      POSTGRES_PORT: "5432"
    labels:
      traefik.enable: "true"
      traefik.http.routers.nc.entrypoints: "web"
      traefik.http.routers.nc.rule: "Host(`nextcloud.{{ ansible_host }}`)"
      traefik.http.services.nc.loadbalancer.server.port: "80"
      traefik.http.middlewares.nc_headers.headers.customRequestHeaders.X-Real-IP: "X-Real-IP"
      traefik.http.middlewares.nc_headers.headers.customRequestHeaders.X-Forwarded-For: "X-Forwarded-For"
      traefik.http.middlewares.nc_headers.headers.customRequestHeaders.X-Forwarded-Proto: "X-Forwarded-Proto"
      traefik.http.routers.nc.middlewares: "nc_headers,nc_redirect"
      traefik.http.middlewares.nc_redirect.redirectregex.permanent: "true"
      traefik.http.middlewares.nc_redirect.redirectregex.regex: "https://(.*)/.well-known/(?:card|cal)dav"
      traefik.http.middlewares.nc_redirect.redirectregex.replacement: "https://$${1}/remote.php/dav"
