lessons_bot_token: ENC[AES256_GCM,data:ZTTSlJOOhwViCqwZX8GcuRprqhW6JXEulxEJqd3DerTp+1bMBiYn3b8/iYk8PQ==,iv:AfhMM/ZeGHH2Vlv1EOyp/zAtbx2gNhUAMiwUJy30fcs=,tag:ymg+OQlQthYKV4EzJ4I6yw==,type:str]
lessons_webhook_secret: ENC[AES256_GCM,data:D9Uy23pQKnnb2sdKtpCkRmYFDALleLmlCvUGivaNqhuL6EkuJH6yvWkguRWEZaOsUIBB+ik/cRYt6ik03bNyGA==,iv:GF/D4TvIoSsf+d4E3xzMtv/UH2MNrpZu/gVhC1Cd+xY=,tag:EMdqYgMLjvpq9i+6iLSdIQ==,type:str]
lessons_allowed_chats: ENC[AES256_GCM,data:t28VvucesbyjOTOUNgEhqjrnCo8tZ30n,iv:xN0cKi1uIF2BNnefXF16XZ2Ny3aqyZnaPFQ1pQn65Ec=,tag:FVc6m0Ja2eEjxs7QTsY/DA==,type:str]
lessons_webhook_path: ENC[AES256_GCM,data:COxvJq+ocCCOXa6z4/k9DMQcSuvBre4dzJLxBj3eWkaluVCt,iv:vE53jI0VzkHdGTQarbcJPszi1/qBKfxq6Xrv/DiImqQ=,tag:3lUikCUilXzop4wAPZ4EZg==,type:str]
lessons_notify_chat: ENC[AES256_GCM,data:WejNECqxbXLtbNqfhGQ=,iv:CM83ugkX2ZaTT0AsKoobiVKMtkVGPHsCrwq8oc3lsXs=,tag:bAo/96h3282+sz1G8rojcQ==,type:str]
lessons_ics_token: ENC[AES256_GCM,data:rGVBaeuwalml9S25gLhrGwuR3Tps7CehTk7G0cJEVPq3fFIuB+DaBlOtMMmcVjgv,iv:/R0JTDBi8msrDA8cjye7yuGPCgESAYOYzK/YA68f5Zg=,tag:h6jblrlqgYZpekqzZfph4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK3YzOGxvclpSWklsOWhx
            Vk5rdUhYYnhObndoM2hFaXNMSHYrVDZmemxRCnN5ZFdSZjlUUWlUZTlUNVc4NW90
            Sm9kMFh6OGhPeHJHQmJFaXdqdzhLTkkKLS0tIFNnbFdpTzhSNXZCTWZJNzNuV1Z1
            VzFtN3JrZW1pWmQ0MjIvQXZGNTlsZnMKFa4Hnma5rvgbcKzSLYJv5vmkgT7PjCtK
            cPYrLqwlkE+65a9xZmwi8C9JidosCZrSNXffsE9ac2XLuZhL1E+ktA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15q64pz4lwtf95vw3afmku5pzuexnsshm6ndfxhhnkqzj6rc3vc9su8fefq
    lastmodified: "2026-07-07T19:49:46Z"
    mac: ENC[AES256_GCM,data:br/Hw/e28fye9IaXZkYY5HWccHncdX34pL34vIuo5YM5eAVfrTXweq1ViV45cROWT6akHkofEOtP5bbtSlWmw2opOEiSuo4yRs+A0vU+hgUYFsYqrvkaZMf6g3BypbOkuWwmrN+fCa8b9ei21pyP72OI7FlS7NxPWOigZCWVnRo=,iv:XV+XHhPgcSC0s1MGWvoRfRG3x8PYn2DQ6QxfDHnTUFk=,tag:DGKeW7sIoqZQBfYh+NREFA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
