lessons_bot_token: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK3YzOGxvclpSWklsOWhx
            Vk5rdUhYYnhObndoM2hFaXNMSHYrVDZmemxRCnN5ZFdSZjlUUWlUZTlUNVc4NW90
            Sm9kMFh6OGhPeHJHQmJFaXdqdzhLTkkKLS0tIFNnbFdpTzhSNXZCTWZJNzNuV1Z1
            VzFtN3JrZW1pWmQ0MjIvQXZGNTlsZnMKFa4Hnma5rvgbcKzSLYJv5vmkgT7PjCtK
            cPYrLqwlkE+65a9xZmwi8C9JidosCZrSNXffsE9ac2XLuZhL1E+ktA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15q64pz4lwtf95vw3afmku5pzuexnsshm6ndfxhhnkqzj6rc3vc9su8fefq
    lastmodified: "2026-05-28T10:47:22Z"
    mac: ENC[AES256_GCM,data:DPJ7DhqkDQNZX/6M63lty61KCktLAsRP6vAE9lMQ1qO+cYg5h5Pw6wAjiy4lEYiDiOx6kApSOdmkYJY8ZLFLbnFWMCVI5EQ1RXvgI9pcHF3u6SDa4msoQKw1rnj6DWKvRoLdY9v6GCKGbKptawHkaFKhe3BhJxmrNHpapxvreCA=,iv:pGBEVHEmgszF36wdJ88l0fPDGynjoL5ha8nrxzvybxs=,tag:yQQ6qXLfvSVEXVTUa2cCEA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
