lessons_bot_token: ENC[AES256_GCM,data:ZTTSlJOOhwViCqwZX8GcuRprqhW6JXEulxEJqd3DerTp+1bMBiYn3b8/iYk8PQ==,iv:AfhMM/ZeGHH2Vlv1EOyp/zAtbx2gNhUAMiwUJy30fcs=,tag:ymg+OQlQthYKV4EzJ4I6yw==,type:str]
lessons_webhook_secret: ENC[AES256_GCM,data:D9Uy23pQKnnb2sdKtpCkRmYFDALleLmlCvUGivaNqhuL6EkuJH6yvWkguRWEZaOsUIBB+ik/cRYt6ik03bNyGA==,iv:GF/D4TvIoSsf+d4E3xzMtv/UH2MNrpZu/gVhC1Cd+xY=,tag:EMdqYgMLjvpq9i+6iLSdIQ==,type:str]
lessons_allowed_chats: ENC[AES256_GCM,data:t28VvucesbyjOTOUNgEhqjrnCo8tZ30n,iv:xN0cKi1uIF2BNnefXF16XZ2Ny3aqyZnaPFQ1pQn65Ec=,tag:FVc6m0Ja2eEjxs7QTsY/DA==,type:str]
lessons_webhook_path: ENC[AES256_GCM,data:wPUzZWRj2axZ+G5vbjcGM5kd9i8JoRqLJ5Bmb0im7V2OBr+8,iv:c+Q5SEviukwwq8hOoqlXE4uk9tDaXzFljwTKWuNuKLM=,tag:ENZ8HEgHBGyif6ATcs9QMg==,type:str]
lessons_notify_chat: ENC[AES256_GCM,data:WejNECqxbXLtbNqfhGQ=,iv:CM83ugkX2ZaTT0AsKoobiVKMtkVGPHsCrwq8oc3lsXs=,tag:bAo/96h3282+sz1G8rojcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK3YzOGxvclpSWklsOWhx
            Vk5rdUhYYnhObndoM2hFaXNMSHYrVDZmemxRCnN5ZFdSZjlUUWlUZTlUNVc4NW90
            Sm9kMFh6OGhPeHJHQmJFaXdqdzhLTkkKLS0tIFNnbFdpTzhSNXZCTWZJNzNuV1Z1
            VzFtN3JrZW1pWmQ0MjIvQXZGNTlsZnMKFa4Hnma5rvgbcKzSLYJv5vmkgT7PjCtK
            cPYrLqwlkE+65a9xZmwi8C9JidosCZrSNXffsE9ac2XLuZhL1E+ktA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15q64pz4lwtf95vw3afmku5pzuexnsshm6ndfxhhnkqzj6rc3vc9su8fefq
    lastmodified: "2026-05-28T16:14:41Z"
    mac: ENC[AES256_GCM,data:Je4Zn+BpMs1QaebdOgS7IFSje6V3aai1UYSgQWnbB7BWoVfmJ2iwKOKO+TrRjIuB9F8RzTbXUbjp4MTDXdMeZb3TvOtSe8THfVNbBIxSYZqxnPLbcYsNNMFyc1IkWZxlTnpYhfyNJhlEJnzRyynTlEIluQDeZsXCHznAmRCHCbo=,iv:9ijXgRGzIH7va9SacHtH1LxjJn7fWJPopZSGKt6j2CI=,tag:U3VgbX91idWtMSu4QnYUXg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
