- name: Create homepage data dir
  ansible.builtin.file:
    path: "{{ app_data_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
    recurse: true
  become: true

- name: Copy homepage services
  ansible.builtin.template:
    src: services.yaml
    dest: "{{ app_data_dir }}/services.yaml"
  register: homepage_config

- name: Copy homepage settings
  ansible.builtin.template:
    src: settings.yaml
    dest: "{{ app_data_dir }}/settings.yaml"

- name: Copy homepage widgets
  ansible.builtin.template:
    src: widgets.yaml
    dest: "{{ app_data_dir }}/widgets.yaml"
  register: homepage_config

- name: homepage container
  community.docker.docker_container:
    name: "{{ app_name }}"
    image: ghcr.io/gethomepage/homepage:latest
    pull: true
    restart: "{{ homepage_config.changed | default(false) }}"
    restart_policy: "unless-stopped"
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - "{{ app_data_dir }}:/app/config"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    env:
      PUID: "1000"
      PGID: "1000"
    labels:
      traefik.enable: "true"
      traefik.http.routers.homepage.rule: "Host(`{{ ansible_host }}`)"
      traefik.http.services.homepage.loadbalancer.server.port: "3000"
