- name: Create homepage data dir
  ansible.builtin.file:
    path: "{{ app_data_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
    recurse: true

- name: Copy homepage services
  ansible.builtin.template:
    src: "{{ template_prefix }}{{ item }}.yaml"
    dest: "{{ app_data_dir }}/{{ item }}.yaml"
  loop:
    - "services"
    - "settings"
    - "widgets"

- name: override labels
  set_fact:
    additional_labels:
      - key: "traefik.http.routers.{{ app_name }}.rule"
        value: "Host(`{{ hostname_prefix }}{{ ansible_host }}`)"

- name: Include labels generator
  ansible.builtin.include_role:
    name: labels_generator

- name: homepage container
  community.docker.docker_container:
    name: "{{ app_name }}"
    image: ghcr.io/gethomepage/homepage:latest
    restart: true
    restart_policy: "unless-stopped"
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - "{{ app_data_dir }}:/app/config"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    env:
      PUID: "1000"
      PGID: "1000"
    labels: "{{ labels }}"
