- name: Copy homepage services
  ansible.builtin.template:
    src: "{{ path_prefix }}{{ item }}.yaml"
    dest: "{{ app_data_dir }}/config/{{ item }}.yaml"
  loop:
    - "bookmarks"
    - "docker"
    - "services"
    - "settings"
    - "widgets"
  vars:
    open_weather_api_key: "{{ lookup('community.general.bitwarden_secrets_manager', '4344ffde-2d4a-46cd-9270-b29b01185379').value }}"

- name: Copy favicon
  ansible.builtin.copy:
    src: "{{ path_prefix }}favicon.ico"
    dest: "{{ app_data_dir }}/images/favicon.ico"

- name: Include labels generator
  ansible.builtin.include_role:
    name: labels_generator
  vars:
    additional_labels:
      - key: "traefik.http.routers.{{ app_name }}.rule"
        value: "Host(`{{ hostname_prefix }}{{ ansible_host }}`)"

- name: homepage container
  community.docker.docker_container:
    name: "{{ app_name }}"
    image: ghcr.io/gethomepage/homepage:latest
    restart: true
    restart_policy: "unless-stopped"
    networks:
      - name: "{{ docker_network }}"
    env:
      HOMEPAGE_ALLOWED_HOSTS: "{{ hostname_prefix }}{{ ansible_host }}"
    volumes:
      - "{{ app_data_dir }}/config:/app/config"
      - "{{ app_data_dir }}/images:/app/public/images"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels: "{{ labels }}"
